---
title: "partial R code for LPS group"
author: "Xiang Yu"
date: "April 1, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = False
```


```{r lps}
library(nlme)
library(dplyr)
library(broom)
setwd("~/LPS TLR mouse")
LPS<-read.delim("LPS_324protein_matrix107mod.txt", header=TRUE)
```

## Data set cleaning and restructuring


```{{r setting factors, echo=FALSE}}
n <- dim(LPS)
t <- 4
ID <- rep(1:n[1],3*t)
Subject <- rep(c(rep(1,n[1]), rep(2,n[1]), rep(4,n[1])),t)
protein_ID <- LPS$Protein.IDs
time <- c(rep(0,3*n[1]), rep(6,3*n[1]), rep(12,3*n[1]), rep(18,3*n[1]))
intensity <- matrix(NA,nrow=n[1]*(3*t),ncol=1)
fit       <- matrix(NA,nrow=n[1],    ncol=9)
for(i in 1:(3*t))
{
   start <- (i-1)*n[1]+1
   end   <-  i*n[1]
   LPS[,i] <- as.numeric(LPS[,i])
   intensity[start:end,1] <- as.numeric(LPS[,i])
}

```


## generalized least squares procedure 

```{r intensity, echo=FALSE}
for(i in 1:n[1])
{
   tempX <- data.frame(X[ID==i,])
   attach(tempX)
   model <- gls(model=intensity ~ factor(time), data=tempX, correlation = corAR1(form = ~ 1 | Subject))
   fit[i,1] <- summary(model)$tTable[1,1]
   fit[i,2] <- summary(model)$tTable[1,4]
   fit[i,3] <- summary(model)$tTable[2,1]
   fit[i,4] <- summary(model)$tTable[2,4]
   fit[i,5] <- summary(model)$tTable[3,1]
   fit[i,6] <- summary(model)$tTable[3,4]
   fit[i,7] <- summary(model)$tTable[4,1]
   fit[i,8] <- summary(model)$tTable[4,4]
   fit[i,9] <- summary(model)$AIC
   detach(tempX)
}
```

## P value adjustment and magnitude sorting
### Omitted at the moment

## output files
### Omitted at the moment
